config/routes.rb
Rails.application.routes.draw do
 
  devise_for :users
  root 'home#index'
  get 'home/index' => 'home#index'
  get 'home/new' => 'home#new'
  get 'home/edit/:id' => 'home#edit'
  post 'home/destroy/:id' => 'home#destroy'
  get 'home/show/:id' => 'home#show'
  post 'home/create' => 'home#create'
  post 'home/update/:id' => 'home#update'
  
  post 'search/' => 'search#index'
  
  post 'home/comment' => 'home#comment'
  post 'home/comment_delete/:id' => 'home#comment_delete'
  
  resources :home do
    member do 
      post 'like' => 'home#like'
      post 'dislike' => 'home#dislike'
    end
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
    belongs_to :place
end

app/models/place.rb
class Place < ActiveRecord::Base    
    mount_uploader :avatar, AvatarUploader
    # validates :avatar, presence: true
    acts_as_votable
    has_many :comments
    
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
         acts_as_voter
end

app/models/vote.rb
class Vote < ActiveRecord::Base    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  #protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  before_action only: [:new, :edit, :update, :destroy, :create]  
  before_action :authenticate_user!, except: [:index]
 
  def index
    @places = Place.all
    @votes = Vote.all.where(vote_flag: true).group(:votable_id).count.sort_by { |k, v| v }.reverse!
    @spot = []
    @votes.each do |id, v|
      @spot << Place.find(id)
    end
  end

  def show
    @place = Place.find(params[:id])
  end

  def new
  end

  def update
    @place = Place.find(params[:id]) 
      if @place.user_id == current_user.id
    @place.title = params[:title]
    @place.content = params[:content]
    @place.map = params[:map]
    @place.month = params[:month]
    @place.ampm = params[:ampm]
    @place.time = params[:time]
    @place.save
  
  end
    redirect_to '/home'
  end

  def edit
    @place = Place.find(params[:id])
    @place.save
  end

  def create
    @place = Place.new
    puts @place
    @place.title = params[:title]
    @place.content = params[:content]
    @place.map = params[:map]
    @place.month = params[:month]
    @place.ampm = params[:ampm]
    @place.time = params[:time]
    @place.user_id = current_user.id
    @place.avatar = params[:avatar]
    @place.save
    
    redirect_to '/'
  end
  
  def like
    @place = Place.find(params[:id])
  
    if ((current_user.voted_up_on? @place) == false)
      @place.upvote_by current_user
      redirect_to "/home/show/#{@place.id}"
    else
      @place.unliked_by current_user
      redirect_to "/home/show/#{@place.id}"
    end
  end
   
  def dislike
    @place = Place.find(params[:id])
      
    if ((current_user.voted_down_on? @place) == false)
      @place.downvote_from current_user
     redirect_to "/home/show/#{@place.id}"
    else
      @place.unliked_by current_user    
      redirect_to "/home/show/#{@place.id}"
    end
  end

  def destroy
    @place = Place.find(params[:id])
    if @place.user_id == current_user.id
      @place.destroy
    end
    redirect_to "/home/index"
  end
  
  def comment
    @comment = Comment.new
    @comment.user_id = current_user.id
    @comment.place_id = params[:place_id]
    @comment.msg = params[:comment]
    @comment.save
    redirect_to :back
  end
  
  def comment_delete
    @comment = Comment.find(params[:id])
    if @comment.user_id == current_user.id
      @comment.destroy
    end
    redirect_to :back
  end
  
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  
    def index
      @searchPlace = Place.where(map: params[:map], ampm: params[:ampm], time: params[:time])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/home/create.html.erb
<h1>Home#create</h1>
<p>Find me in app/views/home/create.html.erb</p>

app/views/home/destroy.html.erb
<h1>Home#destroy</h1>
<p>Find me in app/views/home/destroy.html.erb</p>

app/views/home/edit.html.erb
<form class="form" method="post" action="/home/update/<%= @place.id %>">
            <%= hidden_field_tag :authenticity_token, form_authenticity_token %>

                <tbody>
                    <tr>
                    <h1>글쓰기</h1>
                        </td>
                    </tr>
                <tr>
  <div class="form-group">
    <label for="exampleFormControlInput1">제목</label>
    <input type="text" class="form-control" id="exampleFormControlInput1" placeholder="입력해보시오" name="title">
  </div>
                    </tr>
                    <tr>
                        <td>
                           지역 : 
                        </td>
                        <td>
                            <div class="form-group">
    <select name="map" class="form-control" id="exampleFormControlSelect1">
      <option value="" hidden>지역</option>    
      <option value="마포구">서울 마포구</option>
      <option value="용산구">서울 용산구</option>
      <option value="종로구">서울 종로구</option>
      <option value="강남구">서울 강남구</option>
      <option value="성동구">서울 성동구</option>
      <option value="을왕리">인천 을왕리</option>
    </select>
  </div>
                            
                        </td>
                    </tr>
                    <tr>
                        <td>
                           오전/오후 : 
                        </td>
                        <td>
      <div class="form-group">
    <select name="ampm"class="form-control" id="exampleFormControlSelect1">
      <option value="" hidden>오전/오후</option>    
      <option value="am">오전</option>
      <option value="pm">오후</option>
    </select>
  </div>
 
                        </td>
                    </tr>
                    <tr>
                        <td>
                           시간 : 
                        </td>
                        <td>
  <div class="form-group">
    <select name="time" class="form-control" id="exampleFormControlSelect1">
      <option value="" hidden>시간</option>    
      <option value="1">1시</option>
      <option value="3">3시</option>
      <option value="5">5시</option>
      <option value="7">7시</option>
      <option value="9">9시</option>
      <option value="11">11시</option>
    </select>
  </div>

            
                        
                        </td>
                    </tr>
  <div class="form-group">
    <label for="exampleFormControlTextarea1">리뷰</label>
    <textarea class="form-control" id="exampleFormControlTextarea1" name="content" rows="4"></textarea>
  </div>
<!--                    <tr>-->
<!--                            <h1>수정하기</h1>-->
<!--                        </td>-->
<!--                    </tr>-->
<!--                     <tr>-->
<!--                        <div class="form-group">-->
<!--    <label for="exampleFormControlInput1">제목</label>-->
<!--    <input type="text" class="form-control" id="exampleFormControlInput1" value ="<%= @place.title %>" placeholder="입력해보시오" name="title">-->
<!--  </div>-->

<!--                    </tr>-->
<!--                    <tr>-->
<!--                        <td>-->
<!--                           지역 : -->
<!--                        </td>-->
<!--                        <td>-->
<!--                            div {-->
<!--                        height: 500px;-->
<!--                        width: 50%;-->
<!--                        background-color: powderblue;-->
<!--                        }-->

     
<!--                            <div class="form-group">-->
<!--                                <select name="map" class="form-control" id="exampleFormControlSelect1">-->
<!--                                  <option value="" hidden>지역-서울</option>-->
<!--                                  <option value="<%= @place.map %>" selected hidden><%= @place.map %></option>-->
<!--                                  <option value="마포구">마포구</option>-->
<!--                                  <option value="용산구">용산구</option>-->
<!--                                  <option value="종로구">종로구</option>-->
<!--                                  <option value="강남구">강남구</option>-->
<!--                                  <option value="성동구">성동구</option>-->
<!--                                </select>-->
<!--                            </div>-->
                            
<!--                        </td>-->
<!--                    </tr>-->
                    
<!--                    <tr>-->
<!--                        <td>-->
<!--                           오전/오후 : -->
<!--                        </td>-->
<!--                        div {-->
<!--                    height: 200px;-->
<!--                    width: 50%;-->
<!--                    background-color: powderblue;-->
<!--                    }-->


<!--                        <td>-->
<!--                            <div class="form-group">-->
<!--                            <select class="form-control"  name="ampm"  id="exampleFormControlSelect1">-->
<!--                                <option value="" hidden>오전/오후</option>  -->
<!--                                <option value="<%= @place.ampm %>" selected hidden><%= @place.ampm %></option>-->
<!--                                <option value="am">오전</option>-->
<!--                                <option value="pm">오후</option>-->
<!--                            </select> -->
<!--                            </div>-->
<!--                        </td>-->
<!--                    </tr>-->
<!--                    <tr>-->
<!--                        <td>-->
<!--                           시간 : -->
<!--                        </td>-->
<!--                        div {-->
            <!--    height: 200px;-->
            <!--    width: 50%;-->
            <!--    background-color: powderblue;-->
            <!--}-->

            
<!--                        <td>-->
<!--                            <div class="form-group">-->
<!--                                <select name="time" class="form-control" id="exampleFormControlSelect1">-->
<!--                                      <option value="" hidden>시간</option>-->
<!--                                      <option value="<%= @place.time %>" selected hidden><%= @place.time %></option>-->
<!--                                      <option value="1">1시</option>-->
<!--                                      <option value="3">3시</option>-->
<!--                                      <option value="5">5시</option>-->
<!--                                      <option value="7">7시</option>-->
<!--                                      <option value="9">9시</option>-->
<!--                                      <option value="11">11시</option>-->
<!--                                </select>-->
<!--                              </div>-->
<!--                        </td>-->
<!--                    </tr>-->
<!--                    <div class="form-group">-->
<!--                    <label for="exampleFormControlTextarea1">리뷰</label>-->
<!--                    <textarea class="form-control" id="exampleFormControlTextarea1" name="content" rows="4"><%= @place.content %></textarea>-->
<!--                      </div>-->
                       
                    
              
                    <tr>
                        <td colspan=2 style="text-align:center;">
                            <input type="submit">
                            <input type="reset">
                        </td>
                    </tr>
                    
                </tbody>
            </table>
        </form>

app/views/home/index.html.erb
<head>
  <style>
    .img-fluid{
      width: 400px;
      height: 300px;
    }
  </style>
  <link rel='stylesheet' href="assets/stylesheets/index.css">
</head>
<h3 class="my-4 " id="hotPle">오늘의 핫플</h3>
<div class="row">
  <% @votes.each_with_index do |vote, index| %>
      <div class="text-center col-md-3 col-sm-6 mb-4">
        <a href="/home/show/<%=@spot[index].id%>">
          <p>no. <%= index+1 %> | <%= @spot[index].title %> | 추천수 : <%= vote[1] %></p>
          <img class="img-fluid img-square" src="<%= @spot[index].avatar %>" alt="">
        </a>
      </div>
  <% end %>
</div>
      <!-- /.row -->
<hr>
<center>
  <p class="my-4 " id="recent">최근 게시물</p>
</center>

<div class="row">
  <div class="col-md-10"></div>
  <div class=".col-md-2">
  <div class="newPost">
      <button type="button" class="btn btn-outline-info"><a href="/home/new">새글쓰기</a></button>
  </div>
  </div>
</div>


<div class="post container" style="margin-bottom: 50px;">
  <% @places.each do |p|%>
    <%=p.id%>&nbsp&nbsp&nbsp&nbsp&nbsp
    <a class="title2" href="/home/show/<%=p.id%>"><%=p.title%></a><br>
    <hr>
  <%end%>
</div>
<center>
  <br>
</center>
</span>

app/views/home/new.html.erb
<div class="all3">
<form class="form" method="post" action="/home/create" enctype="multipart/form-data">
            <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
            <table  style="text-align: left;">
            <tbody>
<div class="container">
                    <tr>
                    <h1>글쓰기</h1>
                        </td>
                    </tr>
                <tr>
  <div class="form-group">
    <label for="exampleFormControlInput1">제목</label>
    <input type="text" class="form-control" id="exampleFormControlInput1" placeholder="입력해보시오" name="title">
  </div>
                    </tr>
                    <tr>
                        <td>
                           지역 : 
                        </td>
                        <td>
<div class="form-group">
    <select name="map" class="form-control" id="exampleFormControlSelect1">
      <option value="" hidden>지역</option>    
      <option value="마포구">서울 마포구</option>
      <option value="용산구">서울 용산구</option>
      <option value="종로구">서울 종로구</option>
      <option value="강남구">서울 강남구</option>
      <option value="성동구">서울 성동구</option>
      <option value="을왕리">인천 을왕리</option>
    </select>
  </div>
                            
                        </td>
                    </tr>
                    <tr>
                        <td>
                           오전/오후 : 
                        </td>
                        <td>
      <div class="form-group">
    <select name="ampm"class="form-control" id="exampleFormControlSelect1">
      <option value="" hidden>오전/오후</option>    
      <option value="am">오전</option>
      <option value="pm">오후</option>
    </select>
  </div>
 
                        </td>
                    </tr>
                    <tr>
                        <td>
                           시간 : 
                        </td>
                        <td>
  <div class="form-group">
    <select name="time" class="form-control" id="exampleFormControlSelect1">
      <option value="" hidden>시간</option>    
      <option value="1">1시</option>
      <option value="3">3시</option>
      <option value="5">5시</option>
      <option value="7">7시</option>
      <option value="9">9시</option>
      <option value="11">11시</option>
    </select>
  </div>

            
                        
                        </td>
                    </tr>
  <div class="form-group">
    <label for="exampleFormControlTextarea1">리뷰</label>
    <textarea class="form-control" id="exampleFormControlTextarea1" name="content" rows="4"></textarea>
  </div>
                    <tr>
                        <td colspan=2 style="text-align:center;">
                            <input type="file" name="avatar">
    
                        </td>
                    </tr>
                    
                    <tr>
                        <td colspan=2 style="text-align:center;"><br>
                            <input type="submit">
                            <input type="reset">
                            <button>
                            <a href="/home/index"> <span style="color:black">목록으로</span> </a>
                            </button>
                        
                        </td>
                    </tr>
                    </div>
                </tbody>
            </table>
        </form>
</div>
</div>
<br><br><br><br><br>

app/views/home/show.html.erb
<head>
  <link rel='stylesheet' href="assets/stylesheets/show.css">
</head>

<center>
    <div class="show container" style ='margin-bottom:50px;'>
        <div class="list">
            <a href="/home/index"> 목록으로 </a>
            <a href="/home/edit/<%= @place.id %>"> 수정 </a> 
            <a href="/home/destroy/<%= @place.id %>" data-confirm="게시물을 삭제하시겠습니까?" data-method="post"> 삭제 </a>
        </div>
    <hr>
    <p class="num">작성자&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<%=@place.id%><br>
    제목&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<%=@place.title%><br>
    지역&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<%=@place.map%><br>
    시간&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<%=@place.time%><%=@place.ampm%></p>
    <hr>

  <%= image_tag(@place.avatar.url, :width => 800, :height => 500) if @place.avatar.url.present?%></br>
    <%=@place.content%><br><br><br>
    <a rel="nofollow" data-method="post" href="/home/<%= @place.id %>/like"><button class="btn2" ><img class="btn-img" src="/assets/좋아요.jpg"></a><%= link_to "#{@place.get_upvotes.size}", like_home_path(@place), method: :post %></button>
    <a rel="nofollow" data-method="post" href="/home/<%= @place.id %>/dislike"><button class="btn3"><img class="btn-img3" src="/assets/싫어요.png"></a><%= link_to "#{@place.get_downvotes.size}", dislike_home_path(@place), method: :post %></button>
    <br><br>
 
    <hr>
    <div class="co">
        <% @place.comments.each do |c|%>
            <%= c.msg %>
            <a href="/home/comment_delete/<%= c.id %>" data-method="post">삭제</a>
            <hr>
        <% end %>
    </div>
        <div class="co2">
            댓글달기
            <form action="/home/comment" method="post">
            <input type="hidden" value="<%= @place.id %>" name ="place_id">
            <textarea name="comment" cols="130" rows="3" ></textarea>
            <input type="submit" value="확인">
            </form>
        </div>
    </div>
</center>

app/views/home/update.html.erb
<h1>Home#update</h1>
<p>Find me in app/views/home/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>마타마플</title>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
    
    <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom fonts for this template -->
    <link href="vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Kaushan+Script' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Droid+Serif:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700' rel='stylesheet' type='text/css'>

    <!-- Custom styles for this template -->
    <link href="css/agency.min.css" rel="stylesheet">
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark fixed-top" id="mainNav" style="height: 60px; background-color:#000000;">
      <div class="container">
        <a class="navbar-brand js-scroll-trigger" href="#page-top">Like Lion</a>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav text-uppercase ml-auto ">
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="/home/index/#hotPle">오늘의 핫플</a>
            </li>
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="/home/index/#recent">Recent</a>
            </li>
            <li class="nav-item">
                <% if user_signed_in? %>
                  <%= link_to 'log_out', destroy_user_session_path, method: :delete,  class:"f btn nav-link" %>
            </li>
            <li class="nav-item">
                <% else %>
                  <%= link_to '회원가입', new_user_registration_path, class:"f btn nav-link" %>
            </li>
            <li class="nav-item">      
                  <%= link_to 'log_in', new_user_session_path, class:"f btn nav-link" %>
                <% end %>
            </li>
          </ul>
        </div>
        
      </div>   
    </nav>
    <header class="masthead" style="background-color: #006e96; padding-left:auto; padding-right:auto;">
      <div class="row">
        <div><a class="navbar-brand" href="/home/index" style = "margin-left:30px" ><%= image_tag("logo2.png") %></a></div>
        <div class="container" style = "padding: 30px; margin-left:0px;">
            <!--<a class="navbar-brand" href="/home/index"><%= image_tag("logo2.png") %></a>-->
            <div class="intro-text">
              <div style="text-align:center; font-size:40px; color:white;">
                <span>나만의 공간에서<br>나만의 시간을 말하다</span><hr>
              </div>
            </div>
            <form class="form nav-form" method="post" action="/search" style="padding-left: 300px;">
              <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
                <div class="form-group">
                  <select class="form-control" name="map" style="width:300px">
                    <option value="" hidden>지역</option>    
                    <option value="마포구">서울 마포구</option>
                    <option value="용산구">서울 용산구</option>
                    <option value="종로구">서울 종로구</option>
                    <option value="강남구">서울 강남구</option>
                    <option value="성동구">서울 성동구</option>
                    <option value="을왕리">인천 을왕리</option>
                  </select>
                  <select class="form-control" name="ampm">
                    <option value="" hidden>오전/오후</option>    
                    <option value="am">오전</option>
                    <option value="pm">오후</option>
                  </select>
                  <select class="form-control" name="time">
                    <option value="" hidden>시간</option>    
                    <option value="1">1시</option>
                    <option value="3">3시</option>
                    <option value="5">5시</option>
                    <option value="7">7시</option>
                    <option value="9">9시</option>
                    <option value="11">11시</option>
                  </select>
                </div>
                <button height='20px' width='100px' class="btn btn-outline-light" style="margin-left: 10px;">검색</button>
            </form>
        </div>
     </div>
    </header>
    
    <%= yield %>
    
    <footer style="background-color: #006e96; height:100px;">
      <div class="container">
        <div class="row">
          <div class="col-md-4">
            <span class="copyright">Copyright &copy; Your Website 2018</span>
          </div>
          <div class="col-md-4">
            <ul class="list-inline social-buttons">
              <li class="list-inline-item">
                <a href="#">
                  <i class="fa fa-twitter"></i>
                </a>
              </li>
              <li class="list-inline-item">
                <a href="#">
                  <i class="fa fa-facebook"></i>
                </a>
              </li>
              <li class="list-inline-item">
                <a href="#">
                  <i class="fa fa-linkedin"></i>
                </a>
              </li>
            </ul>
          </div>
          <div class="col-md-4">
            <ul class="list-inline quicklinks">
              <li class="list-inline-item">
                <a href="#">Privacy Policy</a>
              </li>
              <li class="list-inline-item">
                <a href="#">Terms of Use</a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </footer>
    
    
    
        <!-- Bootstrap core JavaScript -->
    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Plugin JavaScript -->
    <script src="vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Contact form JavaScript -->
    <script src="js/jqBootstrapValidation.js"></script>
    <script src="js/contact_me.js"></script>

    <!-- Custom scripts for this template -->
    <script src="js/agency.min.js"></script>
    
  </body>
  
</html>

app/views/search/index.html.erb
<div style="margin-left:100px;margin-right:100px">
  <br><p style="color:#006e96;">검색결과</p>
  
    <% @searchPlace.each do |p| %>
      <a href="/home/show/<%=p.id%>"><%=p.title%></a><br>
      <hr>
    <% end %>
</div>
<br><br><br><br><br><br>